name: GitHub Pages
on: [push]
jobs:
  build-and-deploy:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        poetry-version: [1.3.2]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 🔔 Check out
        uses: actions/checkout@v3

      - name: 🏗️ python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: ⬇️ Python Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: ⬇️ Python Dependencies
        run: poetry install

      - name: 📰 Publish docs
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: ⬆️ MkDocs deploy
        run: poetry run python -m mkdocs gh-deploy --force
