name: Unit Testing
on: [push]
jobs:
  unit-test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        poetry-version: [1.3.2]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 🔔 Check out
        uses: actions/checkout@v3

      - name: 🏗️ python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: ⬇️ Python Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: ⬇️ Python Dependencies
        run: poetry install
      - name: ⬇️ pytest coverage
        run: pip install pytest coverage
      - name: 🏃 pytest
        run: poetry run coverage run -m pytest -v
      - name: 📊 coverage
        run: coverage report -m
